version: 2

models:
  - name: dim_products
    description: "Dimensional model for product-level aggregated sales data."
    columns:
      - name: productid
        description: "Unique identifier for the product."
        tests:
          - not_null
          - unique
      - name: productname
        description: "Name of the product."
      - name: brand
        description: "Brand of the product."
      - name: category
        description: "Category of the product."

