version: 2

models:
  - name: stg_sales
    description: "Staging model for sales data"
    columns:
      - name: SaleID
        description: "Unique identifier for each sale."
        tests:
          - not_null
          - unique
      - name: ProductID
        description: "Identifier for the product."
        tests:
          - not_null
      - name: quantity
        description: "The quantity of items sold"
      - name: price_in_usd
        description: "The price of the item sold"
        tests:
          - assert_no_negative_values

