version: 2

models:
  - name: stg_sales
    description: "Staging model for cleaning and standardizing raw sales data."
    columns:
      - name: SaleID
        description: "Unique identifier for each sale."
        tests:
          - not_null
          - unique
      - name: ProductID
        description: "Identifier for the product."
        tests:
          - not_null
      - name: Quantity
        description: "Quantity of items sold."
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5]
      - name: Price
        description: "Price of the product."
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: ProductID
