name: CI Pipeline

on:
  push:
    branches:
      - feature/*  # Run CI on feature branches
  pull_request:
    branches:
      - main  # Run CI on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run Pytest
        run: |
          pytest tests/
